In [2]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [3]:

X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
poly = PolynomialFeatures(2)

In [5]:
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [7]:
poly3 = PolynomialFeatures(3)
poly3.fit_transform(X)

[1, x1, x2, x1^2, x1*x2, x2^2, x1^3, x1^2 * x2, x2 * x1^2, x2^3]

array([[  1.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.]])

In [10]:
poly3 = PolynomialFeatures(1)
poly3.fit_transform(X)

# [1, x1, x2, x1^2, x1*x2, x2^2, x1^3, x1^2 * x2, x2 * x1^2, x2^3]

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.]])